import * as React from "react";
import { useState } from "react";
import {
  Button,
  Field,
  Textarea,
  makeStyles,
  tokens,
  Text,
} from "@fluentui/react-components";
import { processContent, templates } from "chatgpt_formatter_lib/index";

interface FormatTextProps {
  insertHtml: (html: string) => void;
}

const useStyles = makeStyles({
  container: {
    display: "flex",
    flexDirection: "column",
    padding: "24px",
    gap: "16px",
  },

  header: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },

  title: {
    fontSize: "20px",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
  },

  subtitle: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground3,
  },

  inputSection: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },

  textArea: {
    width: "100%",
    minHeight: "280px",
  },

  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },

  characterCount: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
  },

  button: {
    width: "100%",
  },

  hint: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "18px",
  },
});

const FormatText: React.FC<FormatTextProps> = ({ insertHtml }) => {
  const [rawText, setRawText] = useState<string>("");
  const styles = useStyles();

  const handleFormat = () => {
    try {
      const blocks = processContent(rawText);

      if (!blocks) {
        throw new Error("No content could be processed.");
      }

      const html = templates.defaultTemplate(blocks);
      insertHtml(html);
    } catch (e) {
      console.error("Error formatting content:", e);
    }
  };

  const characterCount = rawText.length;

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <Text className={styles.title}>Format AI Text</Text>

        <Text className={styles.subtitle}>
          Paste your ChatGPT or Claude output and turn it into clean,
          Word-ready formatting.
        </Text>
      </div>

      <div className={styles.inputSection}>
        <Field
          label="Your text"
          hint="Paste the text you want to format."
        >
          <Textarea
            className={styles.textArea}
            size="large"
            value={rawText}
            onChange={(e) => setRawText(e.target.value)}
            placeholder={`Paste your AI-generated text here...

For example:
# Introduction

This is some text generated by ChatGPT.

## Key Points

- First point
- Second point
- Third point`}
            resize="vertical"
          />
        </Field>

        <div className={styles.footer}>
          <Text className={styles.characterCount}>
            {characterCount.toLocaleString()} characters
          </Text>
        </div>
      </div>

      <Button
        appearance="primary"
        size="large"
        className={styles.button}
        disabled={!rawText.trim()}
        onClick={handleFormat}
      >
        Clean & Format
      </Button>

      <Text className={styles.hint}>
        Your formatted content will be inserted directly into the Word
        document.
      </Text>
    </div>
  );
};

export default FormatText;